import type { FragmentManifest } from '@braidlabs/gateway';
import { fieldOwner } from './analysis.js';

/**
 * A fragment descriptor: what an app says about itself.
 *
 * The problem it solves is that a manifest mixes fields owned by different teams. The platform
 * team owns routing and exposure; the app team owns statements about their own app's behavior —
 * and a fact recorded by someone other than the person who knows it drifts, silently, forever.
 *
 * The fix is not a permission matrix over a shared document. It is letting the app publish its own
 * facts next to the code that makes them true, and having the gateway read them.
 *
 * **Always optional.** A fragment that publishes nothing keeps working exactly as it does today —
 * that is the floor, and it must stay the floor, because compat's whole promise is that being
 * composed requires no change to the app. A descriptor is an upgrade for teams who want it, best
 * generated as a build artifact so nobody maintains it by hand.
 */
export interface FragmentDescriptor {
  /** Descriptor format version. Currently `"1"`. */
  braid?: string;
  title?: string;
  description?: string;
  tags?: string[];
  adapter?: string;
  entry?: string;
  element?: string;
  contractVersion?: string;
  events?: Record<string, { detail: string }>;
  /**
   * Context schema versions this app reads and writes, per context type — `@braidlabs/skew` chain
   * versions, not spec versions. Not yet consumed by anything; reserved for the FDC3 work, where
   * a generated descriptor is the inference half of "infer where possible, assume safely
   * elsewhere".
   */
  contexts?: Record<string, number>;
  /**
   * What this app requires of a host, and what it provides back — the self-reported half of the
   * boundary contract.
   *
   * Describable, because a lie here hurts only the liar: an app that overstates what it requires
   * refuses to mount on hosts that would have served it fine. It cannot claim access it was not
   * granted, which is why `pierce` is not describable and this is.
   */
  contract?: {
    version: string;
    requires?: { host?: string; context?: Record<string, number> };
    provides?: { events?: string[]; actions?: string[] };
  };
}

/** Where a fragment publishes its descriptor, relative to its endpoint. */
export const DEFAULT_DESCRIPTOR_PATH = '/.well-known/braid/fragment.json';

/**
 * Fields a descriptor may supply.
 *
 * Generated by one question — *can a lie here hurt anyone but the liar?* A wrong `title` mislabels
 * the liar's own row; a wrong `pierce` puts them on someone else's page. So description is
 * self-reported and exposure never is, and no permission system is required to make that safe.
 */
const DESCRIBABLE_FIELDS = [
  'title',
  'description',
  'tags',
  'adapter',
  'entry',
  'element',
  'contractVersion',
  'events',
  'contract',
] as const;

type DescribableField = (typeof DESCRIBABLE_FIELDS)[number];

export type DescriptorNoteKind = 'applied' | 'disagreement' | 'rejected-field' | 'unreachable' | 'invalid';

export interface DescriptorNote {
  fragmentId: string;
  kind: DescriptorNoteKind;
  field?: string;
  manifestValue?: unknown;
  descriptorValue?: unknown;
  message: string;
}

export interface DescriptorMergeResult {
  manifests: FragmentManifest[];
  notes: DescriptorNote[];
}

/**
 * Merges descriptors into manifests.
 *
 * Precedence, and the reasoning for each rule:
 *
 * 1. **Gateway-owned fields are never merged.** A descriptor that carries `pierce`, `access`, or
 *    `endpoint` is either confused or hostile; either way the value is dropped — and *reported*,
 *    because silently ignoring an attempt tells the operator nothing.
 * 2. **An explicit manifest entry wins.** Setting a field in the manifest is a deliberate human
 *    override and the escape hatch for when an app's self-report is wrong.
 * 3. **Otherwise the descriptor supplies the value.**
 *
 * Disagreements — a field set in both, differently — are surfaced rather than resolved quietly.
 * A disagreement usually means the app moved and the manifest did not, which is exactly the drift
 * this mechanism exists to catch. Resolving it silently in either direction hides the signal.
 */
export function mergeDescriptors(
  manifests: readonly FragmentManifest[],
  descriptors: ReadonlyMap<string, FragmentDescriptor | Error>,
): DescriptorMergeResult {
  const notes: DescriptorNote[] = [];

  const merged = manifests.map((manifest) => {
    const descriptor = descriptors.get(manifest.id);
    if (!descriptor) return manifest;

    if (descriptor instanceof Error) {
      notes.push({
        fragmentId: manifest.id,
        kind: 'unreachable',
        message: `could not read a descriptor for "${manifest.id}": ${descriptor.message}`,
      });
      return manifest;
    }

    return applyDescriptor(manifest, descriptor, notes);
  });

  return { manifests: merged, notes };
}

function applyDescriptor(
  manifest: FragmentManifest,
  descriptor: FragmentDescriptor,
  notes: DescriptorNote[],
): FragmentManifest {
  const result: Record<string, unknown> = { ...manifest };

  for (const [field, value] of Object.entries(descriptor)) {
    if (field === 'braid' || value === undefined) continue;

    if (!isDescribable(field)) {
      notes.push({
        fragmentId: manifest.id,
        kind: 'rejected-field',
        field,
        descriptorValue: value,
        message:
          fieldOwner(field) === 'gateway'
            ? `"${manifest.id}" published "${field}", which only the gateway may set — ignored`
            : `"${manifest.id}" published an unrecognized field "${field}" — ignored`,
      });
      continue;
    }

    const existing = (manifest as unknown as Record<string, unknown>)[field];

    if (existing === undefined) {
      result[field] = value;
      notes.push({
        fragmentId: manifest.id,
        kind: 'applied',
        field,
        descriptorValue: value,
        message: `"${manifest.id}" supplied ${field} from its descriptor`,
      });
      continue;
    }

    if (!deepEqual(existing, value)) {
      notes.push({
        fragmentId: manifest.id,
        kind: 'disagreement',
        field,
        manifestValue: existing,
        descriptorValue: value,
        message:
          `"${manifest.id}" reports ${field} = ${JSON.stringify(value)} but the manifest says ` +
          `${JSON.stringify(existing)} — the manifest wins; check whether the app moved`,
      });
    }
  }

  return result as unknown as FragmentManifest;
}

export interface FetchDescriptorsOptions {
  /** Path on each fragment's endpoint. Defaults to {@link DEFAULT_DESCRIPTOR_PATH}. */
  path?: string;
  /** Per-fragment budget. Defaults to 3000ms. */
  timeoutMs?: number;
  fetch?: typeof fetch;
}

/**
 * Fetches every fragment's descriptor, concurrently.
 *
 * **Called at publish time, never on the request path.** Fetched values fold into the immutable
 * snapshot, so a gateway serving that snapshot never reaches out to a fragment to learn what it
 * is — the availability property of pinning survives intact.
 *
 * A fragment that cannot be reached, or serves something that is not a descriptor, yields an
 * `Error` in the map rather than throwing. Publishing must not fail because one fragment is having
 * a bad day; the previous values stand and the failure is reported.
 *
 * Only manifests with a URL endpoint are probed — a `fetch`-function endpoint is in-process and
 * has no well-known path to read.
 */
export async function fetchDescriptors(
  manifests: readonly FragmentManifest[],
  options: FetchDescriptorsOptions = {},
): Promise<Map<string, FragmentDescriptor | Error>> {
  const doFetch = options.fetch ?? globalThis.fetch;
  const path = options.path ?? DEFAULT_DESCRIPTOR_PATH;
  const timeoutMs = options.timeoutMs ?? 3000;

  const results = new Map<string, FragmentDescriptor | Error>();

  await Promise.all(
    manifests.map(async (manifest) => {
      if (typeof manifest.endpoint !== 'string') return;

      let url: string;
      try {
        // Resolved *relative* to the endpoint — the leading slash is stripped deliberately. An
        // endpoint path is a boundary (`https://internal/apps/billing/` must not reach the rest
        // of that origin), and a root-anchored path would jump outside it and read some other
        // app's descriptor.
        url = new URL(path.replace(/^\//, ''), ensureTrailingSlash(manifest.endpoint)).href;
      } catch {
        return; // an unparseable endpoint is validateRegistry's finding, not this one's
      }

      try {
        const response = await doFetch(url, {
          headers: { accept: 'application/json' },
          signal: AbortSignal.timeout(timeoutMs),
        });

        if (response.status === 404) return; // publishing nothing is the supported default
        if (!response.ok) {
          results.set(manifest.id, new Error(`HTTP ${response.status} from ${url}`));
          return;
        }

        results.set(manifest.id, parseDescriptor(await response.json()));
      } catch (cause) {
        results.set(manifest.id, new Error(cause instanceof Error ? cause.message : String(cause)));
      }
    }),
  );

  return results;
}

function parseDescriptor(value: unknown): FragmentDescriptor {
  if (typeof value !== 'object' || value === null || Array.isArray(value)) {
    throw new Error('a descriptor must be a JSON object');
  }
  return value as FragmentDescriptor;
}

function isDescribable(field: string): field is DescribableField {
  return (DESCRIBABLE_FIELDS as readonly string[]).includes(field);
}

function ensureTrailingSlash(endpoint: string): string {
  return endpoint.endsWith('/') ? endpoint : `${endpoint}/`;
}

function deepEqual(a: unknown, b: unknown): boolean {
  return a === b || JSON.stringify(a ?? null) === JSON.stringify(b ?? null);
}
