import { readFile } from 'node:fs/promises';
import { join } from 'node:path';
import { DetanglePlan } from './plan.js';

/**
 * The gateway: a new app when the shell has no server, middleware when it does.
 *
 * The plan's phrasing is worth keeping in mind while reading this — *"`@braidlabs/gateway` is a
 * library, not a server"*. Nothing here deploys a service. The scaffold exists because a purely
 * client-rendered shell has no process to put middleware into, and something on the host origin has
 * to answer `/__braid/*` for compat fragments.
 *
 * Both paths are generated as **text returned to the caller**, not written here. That keeps the
 * decision about what lands on disk in one place (`write.ts`, with its three refusals) and makes
 * every generated file assertable in a test without touching a filesystem.
 */

export interface GatewayScaffold {
  /** Files to create, keyed by workspace-relative path. */
  files: Record<string, string>;
  /** What a developer still has to do by hand. */
  followUps: string[];
}

/** A new gateway application, for a shell with no server of its own. */
export function scaffoldGatewayApp(plan: DetanglePlan, appName = `${plan.shell?.name ?? 'shell'}-gateway`): GatewayScaffold {
  const shellName = plan.shell?.name ?? 'shell';
  const shellPort = plan.shell?.port ?? 4200;
  const port = 4000;

  const registry = plan.fragments.map((fragment) => ({
    id: fragment.id,
    endpoint: fragment.endpoint ?? `http://localhost:${fragment.port ?? 0}`,
    ...(fragment.pierce.length > 0 ? { pierce: fragment.pierce } : {}),
    ...(fragment.bound ? {} : { bound: false, src: fragment.src ?? '/' }),
  }));

  const main = `import express from 'express';
import { createGateway } from '@braidlabs/gateway';
import { toNodeMiddleware } from '@braidlabs/gateway/node';
import registry from './registry.json' with { type: 'json' };

/**
 * The Braid gateway for ${shellName}.
 *
 * Generated by \`braid detangle\`. Two jobs, both invisible to the app behind it:
 *
 * 1. \`/__braid/frag/:id/*\` is routed to each fragment by id — its realm stub, its JavaScript, its
 *    stylesheet. The fragment never learns it is embedded.
 * 2. A document request for a \`pierce\` route is composed: the gateway fetches the shell's HTML and
 *    each fragment's concurrently and interleaves them, so fragment markup is in the first response.
 *
 * The second only pays off if the shell server-renders. A client-rendered shell still composes —
 * fragments are fetched client-side — but the first paint will not contain them.
 */
const app = express();
const port = Number(process.env.PORT ?? ${port});

app.use(toNodeMiddleware(createGateway({ mode: 'production', registry })));

/**
 * The shell, behind the gateway.
 *
 * In development this proxies to the shell's own dev server so its live reload survives; in
 * production, replace it with the shell's static build or its SSR handler.
 */
app.use(
  '/',
  (await import('http-proxy-middleware')).createProxyMiddleware({
    target: process.env.SHELL_ORIGIN ?? 'http://localhost:${shellPort}',
    changeOrigin: true,
    ws: true,
  }),
);

app.listen(port, () => console.log(\`${appName} listening on http://localhost:\${port}\`));
`;

  const projectJson = `${JSON.stringify(
    {
      name: appName,
      $schema: '../../node_modules/nx/schemas/project-schema.json',
      projectType: 'application',
      sourceRoot: `apps/${appName}/src`,
      targets: {
        serve: {
          executor: 'nx:run-commands',
          options: { command: `node apps/${appName}/src/main.js` },
        },
      },
    },
    null,
    2,
  )}\n`;

  return {
    files: {
      [`apps/${appName}/src/main.ts`]: main,
      [`apps/${appName}/src/registry.json`]: `${JSON.stringify(registry, null, 2)}\n`,
      [`apps/${appName}/project.json`]: projectJson,
    },
    followUps: [
      `install express and http-proxy-middleware if this workspace does not already have them`,
      `for production, replace the dev proxy in apps/${appName}/src/main.ts with the shell's build output`,
      `${shellName} is client-rendered: fragments will not be in the first response until it server-renders`,
    ],
  };
}

/**
 * Where the gateway middleware goes in a server that already exists.
 *
 * This **finds the insertion point and reports it**; it does not rewrite the file. The plan says to
 * insert `app.use` first and to "warn if it cannot find the express instance, rather than a guess at
 * the file's structure" — and having read a few of these, the honest position is that the guess is
 * unreliable often enough that it should not be automated at all. A server entry point is the file
 * most likely to be hand-tuned, and it is three lines to add.
 *
 * So: name the file, name the line, and give the exact text.
 */
export interface MiddlewareInsertion {
  file: string;
  /** 1-indexed line the `app.use` should go before, when one could be identified. */
  line?: number;
  snippet: string;
  note: string;
}

const SERVER_FILES = ['src/server.ts', 'src/main.server.ts', 'server.ts', 'src/server.js'];

export async function findMiddlewareInsertion(
  workspaceRoot: string,
  shellRoot: string,
): Promise<MiddlewareInsertion | undefined> {
  for (const candidate of SERVER_FILES) {
    const relative = `${shellRoot}/${candidate}`;
    let source: string;
    try {
      source = await readFile(join(workspaceRoot, relative), 'utf-8');
    } catch {
      continue;
    }

    const lines = source.split('\n');
    /**
     * The first `app.use(` — the gateway has to see requests before anything else answers them,
     * and in particular before a static handler or an SSR catch-all does.
     */
    const index = lines.findIndex((line) => /\bapp\s*\.\s*use\s*\(/.test(line));

    return {
      file: relative,
      ...(index >= 0 ? { line: index + 1 } : {}),
      snippet: [
        `import { createGateway } from '@braidlabs/gateway';`,
        `import { toNodeMiddleware } from '@braidlabs/gateway/node';`,
        `import registry from './registry.json' with { type: 'json' };`,
        ``,
        `app.use(toNodeMiddleware(createGateway({ mode: 'production', registry })));`,
      ].join('\n'),
      note:
        index >= 0
          ? 'insert before the first app.use — the gateway must see a request before anything else answers it'
          : 'no app.use found; add the middleware wherever this server registers its first handler',
    };
  }

  return undefined;
}
